services:
  postgres:
    image: postgres:17-alpine
    container_name: gina_postgres2
    restart: always
    environment:
      POSTGRES_DB: gina_dev
      POSTGRES_USER: gina_user
      POSTGRES_PASSWORD: gina_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gina_user -d gina_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: