services:
  postgres:
    image: postgres:17-alpine
    container_name: shop_postgres1
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5444:5432"
    volumes:
      - postgres_shop:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_shop: